package gamemessage;

public enum GameMessageType {
    GAME_INITIALIZING,
    BOARD_INITIALIZED,
    DICE_INITIALIZED,
    PLAYERS_CREATED,
    GAME_STARTING,
    TOSS_STARTING,
    DICE_ROLLED,
    TOSS_WON,
    TURN_STARTED
}
