package gamemessage;

public enum GameMessageType {
    GAME_INITIALIZING,
    BOARD_INITIALIZED,
    DICE_INITIALIZED,
    PLAYERS_CREATED,
    GAME_STARTING,
    TOSS_STARTING,
    DICE_ROLLED,
    TOSS_TIED,
    TOSS_WON,
    ROUND_STARTED,
    TURN_STARTED,
    TURN_ROLLED,
    NO_PIECE_MOVABLE,
    PIECE_MOVED,
    PIECE_ENTERED_BOARD,
    PIECE_ENTERED_HOME_STRAIGHT,
    PIECE_REACHED_HOME,
    THIRD_SIX_VOIDED
}
